import { AlertTriangle, ArrowRight, Bell, Check, Clock3, ShieldAlert, X } from "lucide-react";
import { Link } from "react-router-dom";
import WorkspaceLayout from "@/components/WorkspaceLayout";
import { useContractLens } from "@/components/ContractLensContext";
import { PageHeader, SectionTitle, StatusPill } from "@/components/MvpUi";

export default function Alerts() {
  const { alerts, markAlertRead, dismissAlert } = useContractLens();
  const unread = alerts.filter((alert) => !alert.read).length;
  return <WorkspaceLayout title="Alerts"><PageHeader eyebrow="Notification center" title="Nothing important slips by" description="Upcoming deadlines, overdue actions, and contract review signals in one place." action={<div className="flex items-center gap-2 rounded-xl bg-white/[0.08] px-3 py-2 text-[10px] font-bold text-[#cde7df]"><Bell className="h-4 w-4" /> {unread} unread</div>} /><section className="mt-5 rounded-2xl border border-[#e7edf1] bg-white p-5 shadow-[0_5px_18px_rgba(34,52,68,0.025)] md:p-6"><SectionTitle title="Your alerts" description="Click an alert to mark it read or open its source contract." action={<button onClick={() => alerts.forEach((alert) => markAlertRead(alert.id))} className="text-[10px] font-bold text-[#4a9b87]">Mark all read</button>} /><div className="mt-5 space-y-3">{alerts.length === 0 && <div className="py-10 text-center text-[12px] text-[#8b9ba5]">You’re all caught up.</div>}{alerts.map((alert) => <div key={alert.id} className={`flex flex-col gap-4 rounded-xl border p-4 md:flex-row md:items-center ${alert.read ? "border-[#edf1f4] bg-white" : alert.type === "Overdue" ? "border-[#f1dfd5] bg-[#fffaf7]" : alert.type === "Review" ? "border-[#f2e3ca] bg-[#fffaf3]" : "border-[#dfe9f2] bg-[#f7faff]"}`}><div className={`flex h-9 w-9 shrink-0 items-center justify-center rounded-xl ${alert.type === "Overdue" ? "bg-[#ffe8dc] text-[#cd7357]" : alert.type === "Review" ? "bg-[#fff0cf] text-[#c89137]" : "bg-[#e6efff] text-[#607dcc]"}`}>{alert.type === "Overdue" ? <AlertTriangle className="h-4 w-4" /> : alert.type === "Review" ? <ShieldAlert className="h-4 w-4" /> : <Clock3 className="h-4 w-4" />}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="text-[12px] font-bold text-[#405768]">{alert.title}</h3><StatusPill tone={alert.type === "Overdue" ? "rose" : alert.type === "Review" ? "amber" : "blue"}>{alert.type}</StatusPill></div><p className="mt-1 text-[10px] text-[#8c9ba7]">{alert.detail}</p></div><div className="flex shrink-0 items-center gap-2"><Link to={`/contracts/${alert.contractId}`} onClick={() => markAlertRead(alert.id)} className="inline-flex items-center gap-1 text-[10px] font-bold text-[#4a8d7e]">View source <ArrowRight className="h-3 w-3" /></Link>{!alert.read && <button onClick={() => markAlertRead(alert.id)} className="rounded-lg p-1.5 text-[#6ca390] hover:bg-[#eaf7f2]" title="Mark read"><Check className="h-4 w-4" /></button>}<button onClick={() => dismissAlert(alert.id)} className="rounded-lg p-1.5 text-[#b2bec5] hover:bg-[#f7f9fa]" title="Dismiss"><X className="h-4 w-4" /></button></div></div>)}</div></section></WorkspaceLayout>;
}
