import { AlertTriangle, ArrowRight, BarChart3, CalendarClock, CheckCircle2, Clock3, FileText, FolderOpen, GitCompareArrows, ListChecks, ShieldAlert, Sparkles } from "lucide-react";
import { Link } from "react-router-dom";
import WorkspaceLayout from "@/components/WorkspaceLayout";
import { useContractLens } from "@/components/ContractLensContext";
import { MetricCard, PageHeader, SectionTitle, SourceBadge, StatusPill } from "@/components/MvpUi";
import { activityItems } from "@/components/ContractLensData";

export default function Dashboard() {
  const { contracts, obligations } = useContractLens();
  const pending = obligations.filter((item) => item.status === "Pending").length;
  const overdue = obligations.filter((item) => item.status === "Overdue").length + 1;
  return <WorkspaceLayout title="Dashboard"><PageHeader eyebrow="Workspace overview" title="Good morning, Avery" description="Your contracts, obligations, and review work at a glance." action={<Link to="/contracts/upload" className="inline-flex h-10 items-center gap-2 rounded-xl bg-[#c8f2e4] px-4 text-[12px] font-bold text-[#123d3a] hover:bg-[#e0faf1]">Upload contract <ArrowRight className="h-4 w-4" /></Link>} />
    <section className="mt-5 grid grid-cols-2 gap-3 md:grid-cols-3 xl:grid-cols-6"><MetricCard label="Total contracts" value={String(contracts.length + 20)} detail="+3 this month" icon={FolderOpen} onClick={() => {}} /><MetricCard label="Active contracts" value={String(contracts.filter((item) => item.status === "Active").length + 15)} detail="62% of portfolio" icon={CheckCircle2} tone="blue" /><MetricCard label="Expiring soon" value="03" detail="Next 90 days" icon={Clock3} tone="lilac" /><MetricCard label="Pending obligations" value={String(pending + 13)} detail="4 due this week" icon={ListChecks} tone="mint" /><MetricCard label="Overdue" value={String(overdue)} detail="Needs action" icon={AlertTriangle} tone="peach" /><MetricCard label="Requires review" value="07" detail="2 high priority" icon={ShieldAlert} tone="peach" /></section>
    <section className="mt-5 grid gap-5 xl:grid-cols-[1.2fr_0.8fr]"><div className="rounded-2xl border border-[#e7edf1] bg-white p-5 shadow-[0_5px_18px_rgba(34,52,68,0.025)] md:p-6"><SectionTitle title="Upcoming deadlines" description="The next actions across your active agreements" action={<Link to="/obligations" className="text-[10px] font-bold text-[#3b8272]">View all →</Link>} /><div className="mt-5 divide-y divide-[#edf1f4]">{obligations.slice(0, 4).map((item) => <div key={item.id} className="flex items-center gap-3 py-3.5 first:pt-0"><div className="flex h-10 w-10 shrink-0 flex-col items-center justify-center rounded-xl bg-[#f7f9fb] text-center leading-none"><span className="text-[8px] font-bold text-[#98a5b0]">{item.deadline.split(" ")[0]}</span><span className="mt-1 text-[14px] font-bold text-[#384b5d]">{item.deadline.split(" ")[1]?.replace(",", "")}</span></div><div className="min-w-0 flex-1"><p className="truncate text-[12px] font-semibold text-[#304356]">{item.title}</p><p className="mt-1 truncate text-[10px] text-[#8c9ba7]">{item.party} · {item.source}</p></div><StatusPill tone={item.priority === "High" ? "rose" : item.priority === "Medium" ? "amber" : "blue"}>{item.priority}</StatusPill></div>)}</div></div><div className="rounded-2xl border border-[#e7edf1] bg-white p-5 shadow-[0_5px_18px_rgba(34,52,68,0.025)] md:p-6"><SectionTitle title="Upcoming renewals" description="Notice windows you should not miss" /><div className="mt-5 space-y-3"><div className="rounded-xl border border-[#f2e3ca] bg-[#fffaf3] p-4"><div className="flex items-center justify-between"><span className="text-[10px] font-bold uppercase tracking-[0.1em] text-[#b17a32]">12 days</span><CalendarClock className="h-4 w-4 text-[#d49a4a]" /></div><p className="mt-3 text-[12px] font-bold text-[#5c4837]">Northstar Logistics MSA</p><p className="mt-1 text-[10px] text-[#a28b73]">Notice window opens Nov 02, 2024</p></div><div className="rounded-xl border border-[#e1ebf5] bg-[#f7faff] p-4"><div className="flex items-center justify-between"><span className="text-[10px] font-bold uppercase tracking-[0.1em] text-[#5f79ba]">41 days</span><CalendarClock className="h-4 w-4 text-[#6f8dd6]" /></div><p className="mt-3 text-[12px] font-bold text-[#425979]">Orbit Analytics DPA</p><p className="mt-1 text-[10px] text-[#8395ad]">Renewal window opens Nov 25, 2024</p></div></div></div></section>
    <section className="mt-5 grid gap-5 xl:grid-cols-[1.1fr_0.9fr]"><div className="rounded-2xl border border-[#e7edf1] bg-white p-5 md:p-6"><SectionTitle title="Recent contracts" description="Latest document activity" action={<Link to="/contracts" className="text-[10px] font-bold text-[#3b8272]">Open portfolio →</Link>} /><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[540px] text-left"><thead><tr className="border-b border-[#edf1f4] text-[9px] font-bold uppercase tracking-[0.12em] text-[#a0acb5]"><th className="pb-3">Contract</th><th className="pb-3">Status</th><th className="pb-3">Risk</th></tr></thead><tbody>{contracts.slice(0, 4).map((contract) => <tr key={contract.id} className="border-b border-[#f0f3f5] last:border-0"><td className="py-3"><Link to={`/contracts/${contract.id}`} className="flex items-center gap-2.5"><div className={`flex h-8 w-8 items-center justify-center rounded-lg text-[9px] font-bold ${contract.color}`}>{contract.icon}</div><div><p className="text-[11px] font-bold text-[#33485b]">{contract.name}</p><p className="mt-0.5 text-[9px] text-[#91a0ab]">{contract.type}</p></div></Link></td><td><StatusPill tone={contract.status === "Active" ? "green" : contract.status === "Renewal soon" ? "amber" : "blue"}>{contract.status}</StatusPill></td><td className="text-[10px] font-semibold text-[#bc6a55]">{contract.risk}</td></tr>)}</tbody></table></div></div><div className="rounded-2xl border border-[#e7edf1] bg-white p-5 md:p-6"><SectionTitle title="Needs your attention" description="Potential risks surfaced by ContractLens" /><div className="mt-5 space-y-3"><Link to="/contracts/acme-cloud?tab=risks" className="group block rounded-xl border border-[#f2e3ca] bg-[#fffaf3] p-3.5"><div className="flex gap-3"><div className="flex h-7 w-7 shrink-0 items-center justify-center rounded-lg bg-[#ffe8dc] text-[#cd7357]"><AlertTriangle className="h-3.5 w-3.5" /></div><div className="flex-1"><p className="text-[11px] font-bold text-[#5c4837]">Ambiguous termination clause</p><p className="mt-1 text-[10px] text-[#a28b73]">Acme Cloud · Section 8.2 · Page 10</p></div><ArrowRight className="h-3.5 w-3.5 text-[#bda486]" /></div></Link><Link to="/compare" className="group block rounded-xl border border-[#e1eaf4] bg-[#f7faff] p-3.5"><div className="flex gap-3"><div className="flex h-7 w-7 shrink-0 items-center justify-center rounded-lg bg-[#e6efff] text-[#607dcc]"><GitCompareArrows className="h-3.5 w-3.5" /></div><div className="flex-1"><p className="text-[11px] font-bold text-[#425979]">Material version change</p><p className="mt-1 text-[10px] text-[#8395ad]">Northstar MSA · Liability cap</p></div><ArrowRight className="h-3.5 w-3.5 text-[#8395ad]" /></div></Link></div></div></section>
    <section className="mt-5 grid gap-5 lg:grid-cols-3"><div className="rounded-2xl border border-[#e7edf1] bg-white p-5 md:p-6"><SectionTitle title="Contract status" /><div className="mt-5 flex items-center gap-5"><div className="relative flex h-28 w-28 items-center justify-center rounded-full" style={{ background: "conic-gradient(#5eaa95 0 68%, #e4a76b 68% 82%, #829bd6 82% 100%)" }}><div className="flex h-20 w-20 items-center justify-center rounded-full bg-white text-center"><div><div className="text-[20px] font-bold text-[#304758]">24</div><div className="text-[8px] font-bold uppercase text-[#9aa8b2]">total</div></div></div></div><div className="space-y-2 text-[10px] font-semibold text-[#70818e]"><div><i className="mr-2 inline-block h-2 w-2 rounded-full bg-[#5eaa95]" />Active 68%</div><div><i className="mr-2 inline-block h-2 w-2 rounded-full bg-[#e4a76b]" />Renewing 14%</div><div><i className="mr-2 inline-block h-2 w-2 rounded-full bg-[#829bd6]" />Processing 18%</div></div></div></div><div className="rounded-2xl border border-[#e7edf1] bg-white p-5 md:p-6"><SectionTitle title="Obligation status" /><div className="mt-6 space-y-4">{[{ label: "Completed", value: 54, color: "bg-[#6bb39d]" }, { label: "Pending", value: 32, color: "bg-[#e7b16f]" }, { label: "Overdue", value: 14, color: "bg-[#da7d73]" }].map((item) => <div key={item.label}><div className="mb-1.5 flex justify-between text-[10px] font-semibold text-[#718391]"><span>{item.label}</span><span>{item.value}%</span></div><div className="h-2 rounded-full bg-[#f0f3f5]"><div className={`h-2 rounded-full ${item.color}`} style={{ width: `${item.value}%` }} /></div></div>)}</div></div><div className="rounded-2xl border border-[#e7edf1] bg-white p-5 md:p-6"><SectionTitle title="Recent activity" action={<BarChart3 className="h-4 w-4 text-[#9aa8b2]" />} /><div className="mt-4 space-y-3.5">{activityItems.map((item) => <div key={item.action} className="flex gap-2.5"><div className="mt-0.5 flex h-6 w-6 shrink-0 items-center justify-center rounded-lg bg-[#e5f8f1] text-[#4d9e89]"><Sparkles className="h-3 w-3" /></div><div><p className="text-[10px] font-semibold text-[#536978]">{item.action}</p><p className="mt-0.5 text-[9px] text-[#9aa8b2]">{item.detail} · {item.time}</p></div></div>)}</div></div></section>
  </WorkspaceLayout>;
}
